### ISSUE TITLE
MD5 is depreciated

### ISSUE THREAD

**Issue by kalegood** [asdfjkl/pgn2anki#1]
https://docs.python.org/2/library/md5.html

**Comment by kalegood** [comment]
changes:
Line 6: import md5
Line 49: m = md5.new (fen_string)
becomes
import hashlib
m = hashlib.md5(fen_string)

**Comment by asdfjkl** [comment]
Since Anki has the ability to display FEN strings (using either Ankidroid, or a plugin on the desktop version), pgn2anki no loner creates graphics, but directly cards with FEN strings.

Hence, md5 is no longer required, and the dependency has been removed from the python script.

Note that for Windows I also provide a binary (based on cx_freeze)
