### ISSUE TITLE
Issues with PIL

### ISSUE THREAD

**Issue by kalegood** [asdfjkl/pgn2anki#3]
I'm having some issues with pil, and, from what I can find, pillow is a better replacement. 
However, I'm currently working on avoiding that entirely, as I think it would be better to simply output FEN strings into a CSV and [use this deck](https://ankiweb.net/shared/info/1176122148) to display them, avoiding images altogether.

**Comment by asdfjkl** [comment]
Indeed, PIL can be a pain to install.

I went with https://ankiweb.net/shared/info/2923601993 instead of the linked deck, which is also quite easy to install. In particular, the deck has issues with Ankidroid (Android), whereas Ankidroid has support for FEN strings built-in.

In other words, PIL is no longer needed.

For Windows there is even a binary now.
